# Generated by Django 3.0.1 on 2019-12-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Zip', models.CharField(max_length=6)),
                ('Email', models.EmailField(max_length=254)),
                ('Web', models.CharField(max_length=20)),
            ],
        ),
    ]
