# Generated by Django 3.0.1 on 2019-12-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191222_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
