# Generated by Django 3.0.1 on 2019-12-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191223_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='employee_id',
        ),
    ]
