# Generated by Django 3.0.1 on 2019-12-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_users_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Company_Name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Web',
            new_name='web',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Zip',
            new_name='zip',
        ),
    ]
